#!/usr/bin/env python3
"""
Example: Integrate Affiliate Links into Blog Generation Workflow

This shows how to modify your existing blog generation to automatically
include affiliate links.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils.blog_affiliate_integration import BlogAffiliateIntegration


# ===== EXAMPLE 1: Modify Existing generate_batch_posts.py =====

def example_batch_generation_integration():
    """
    Show how to add to existing generate_batch_posts.py workflow.
    """
    print("═" * 60)
    print("EXAMPLE 1: Batch Post Generation with Auto-Affiliate Links")
    print("═" * 60)

    # Initialize integrator ONCE at the start of your batch generation
    integrator = BlogAffiliateIntegration()

    # Example post configuration (from your existing BATCH_POSTS)
    post_config = {
        "product_name": "ClickUp",
        "title": "Complete Project Management Guide for Government Contractors",
        "slug": "clickup-project-management-government-contractors",
        "category": "Project Management",
    }

    # Simulated blog content (normally generated by your ContentAgent)
    generated_content = """
# Complete Project Management Guide for Government Contractors

Government contractors face unique challenges in project management. Between
strict compliance requirements, complex team coordination, and tight deadlines,
you need a robust solution.

## Key Requirements

Federal contractors need:
- Task tracking and assignment
- Team collaboration tools
- Document management
- Compliance tracking
- Timeline management

## Choosing the Right Tool

When selecting project management software, consider...
"""

    print("\n1. Generated base content ✓")
    print(f"   Title: {post_config['title']}")
    print(f"   Length: {len(generated_content)} characters")

    # ADD THIS TO YOUR WORKFLOW: Enhance with affiliates
    result = integrator.enhance_post(
        title=post_config["title"],
        content=generated_content,
        slug=post_config["slug"],
        max_matches=3
    )

    print(f"\n2. Enhanced with affiliates ✓")
    print(f"   Added: {result['affiliate_count']} affiliate recommendations")
    print(f"   Programs: {', '.join([m['name'] for m in result['matches']])}")

    # The enhanced content is ready to publish
    final_content = result["content"]

    print(f"\n3. Final content ready ✓")
    print(f"   Total length: {len(final_content)} characters")
    print(f"   Has affiliates: {result['has_affiliates']}")

    return final_content


# ===== EXAMPLE 2: Integrate with ContentAgent =====

def example_content_agent_integration():
    """
    Show how to modify ContentAgent.generate_post() method.
    """
    print("\n" + "═" * 60)
    print("EXAMPLE 2: ContentAgent Integration")
    print("═" * 60)

    integrator = BlogAffiliateIntegration()

    # In your ContentAgent.generate_post() method, ADD THIS at the end:
    """
    # After generating base content:
    # base_content = self._generate_with_ollama(topic, product)

    # ADD THIS:
    enhanced = integrator.enhance_post(
        title=topic.title,
        content=base_content,
        slug=slug,
        max_matches=3
    )

    # Use enhanced content instead of base_content:
    post.content = enhanced['content']
    post.has_affiliates = enhanced['has_affiliates']
    post.affiliate_count = enhanced['affiliate_count']
    """

    print("\nCode to add to ContentAgent.generate_post():")
    print("""
    from utils.blog_affiliate_integration import BlogAffiliateIntegration

    integrator = BlogAffiliateIntegration()  # Initialize once

    # After generating base content:
    enhanced = integrator.enhance_post(
        title=topic.title,
        content=base_content,
        slug=slug
    )

    post.content = enhanced['content']
    """)


# ===== EXAMPLE 3: Standalone Affiliate Section =====

def example_standalone_affiliate_section():
    """
    Create just the affiliate section for manual insertion.
    """
    print("\n" + "═" * 60)
    print("EXAMPLE 3: Standalone Affiliate Section")
    print("═" * 60)

    integrator = BlogAffiliateIntegration()

    # For when you want just the recommendations without full integration
    from agents.unified_affiliate_agent import UnifiedAffiliateAgent

    agent = UnifiedAffiliateAgent()

    content = "cybersecurity compliance for federal contractors CMMC requirements"
    matches = agent.find_best_matches(content, "Cybersecurity", max_matches=3)

    if matches:
        section = agent.format_affiliate_section(matches)
        print("\nGenerated affiliate section:")
        print(section[:500] + "...")


# ===== EXAMPLE 4: Resource Pages =====

def example_resource_page_generation():
    """
    Generate category-specific resource pages.
    """
    print("\n" + "═" * 60)
    print("EXAMPLE 4: Category Resource Pages")
    print("═" * 60)

    integrator = BlogAffiliateIntegration()

    # Create a "Best Cybersecurity Tools" resource page
    cybersecurity_tools = integrator.get_pre_approved_links("security", count=8)

    print("\nGenerated resource page with pre-approved links:")
    print(f"Found {len(cybersecurity_tools)} security tools\n")

    for i, tool in enumerate(cybersecurity_tools[:5], 1):
        print(f"{i}. {tool['name']}")
        print(f"   Commission: {tool['commission']}%")
        print(f"   Network: {tool['network']}")
        print(f"   Link: {tool['link'][:50]}...\n")


# ===== EXAMPLE 5: Quick Integration =====

def example_quick_one_liner():
    """
    Simplest possible integration - one line of code.
    """
    print("\n" + "═" * 60)
    print("EXAMPLE 5: One-Line Integration")
    print("═" * 60)

    from utils.blog_affiliate_integration import BlogAffiliateIntegration

    # ONE LINE to add affiliates to any content:
    enhanced = BlogAffiliateIntegration().enhance_post(
        "Best PM Tools",
        "Project management is essential for contractors..."
    )

    print("\nOne-liner:")
    print("""
    enhanced = BlogAffiliateIntegration().enhance_post(title, content)
    final_content = enhanced['content']
    """)

    print(f"\nResult: {enhanced['affiliate_count']} affiliates added")


def main():
    """Run all integration examples."""
    print("\n🔗 Blog-Affiliate Integration Examples\n")

    # Example 1: Batch generation
    example_batch_generation_integration()

    # Example 2: ContentAgent integration
    example_content_agent_integration()

    # Example 3: Standalone section
    example_standalone_affiliate_section()

    # Example 4: Resource pages
    example_resource_page_generation()

    # Example 5: Quick integration
    example_quick_one_liner()

    # Summary
    print("\n" + "═" * 60)
    print("INTEGRATION COMPLETE")
    print("═" * 60)
    print("\n✓ All examples demonstrated")
    print("✓ Ready to integrate into your blog workflow")
    print("\nChoose the integration method that best fits your workflow!")


if __name__ == "__main__":
    main()
