import type { PartnerProgram } from './partners'

export const partnerProgramsGenerated: PartnerProgram[] = [  {
    slug: '1password',
    name: '1Password',
    platform: 'PartnerStack',
    category: 'Cybersecurity & Identity',
    description: 'The 1Password service from 1Password Inc offers a password management solution that securely stores and generates unique passwords for users\' online accounts.',
    excerpt: 'The 1Password service from 1Password Inc offers a password management solution that securely stores and generates unique passwords for...',
    keywords: ['gjh inc', 'start.1password', '1password'],
    url: 'https://1password.partnerlinks.io/vgdsetz1mrpr',
    logo: '',
    cta: 'Explore 1Password',
  },
  {
    slug: 'activecampaign',
    name: 'ActiveCampaign',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'ActiveCampaign is a marketing automation and customer relationship management platform designed for businesses to manage contacts, automate workflows, and track engagement metrics.',
    excerpt: 'ActiveCampaign is a marketing automation and customer relationship management platform designed for businesses to manage contacts,...',
    keywords: ['gjh inc', 'activecampaign'],
    url: 'https://try.activecampaign.com/88zsx386ant8',
    logo: '',
    cta: 'Explore ActiveCampaign',
  },
  {
    slug: 'adcreative-ai',
    name: 'AdCreative.ai',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'AdCreative.ai is a digital marketing tool offered by GJH Inc that assists users in generating and optimizing creative assets for online advertising campaigns.',
    excerpt: 'AdCreative.ai is a digital marketing tool offered by GJH Inc that assists users in generating and optimizing creative assets for online...',
    keywords: ['gjh inc', 'adcreative.ai'],
    url: 'https://free-trial.adcreative.ai/k6xjb7lusnq1',
    logo: '',
    cta: 'Explore AdCreative.ai',
  },
  {
    slug: 'aircall-inc',
    name: 'Aircall Inc.',
    platform: 'PartnerStack',
    category: 'Communication & Collaboration',
    description: 'Aircall Inc.',
    excerpt: 'Aircall Inc.',
    keywords: ['gjh inc', 'aircall inc.', 'aircall'],
    url: 'https://get.aircall.io/qnsq9ee62fgn',
    logo: '',
    cta: 'Explore Aircall Inc.',
  },
  {
    slug: 'angelbliss',
    name: 'Angelbliss',
    platform: 'Impact',
    category: 'Other',
    description: 'The Angelbliss app provides users with a platform for tracking and managing their mental well-being through guided meditations and mood-tracking features.',
    excerpt: 'The Angelbliss app provides users with a platform for tracking and managing their mental well-being through guided meditations and...',
    keywords: ['angelbliss.us', 'health', 'app', 'angelbliss'],
    url: 'https://angelbliss.pxf.io/c/5873369/1745569/20350',
    logo: '',
    cta: 'Explore Angelbliss',
  },
  {
    slug: 'answering-service-care-llc',
    name: 'Answering Service Care, LLC',
    platform: 'PartnerStack',
    category: 'Operations',
    description: 'Answering Service Care, LLC provides business operations support services, including answering and managing phone calls for companies.',
    excerpt: 'Answering Service Care, LLC provides business operations support services, including answering and managing phone calls for companies.',
    keywords: ['gjh inc', 'answering service care, llc', 'answeringservicecare'],
    url: 'https://partners.answeringservicecare.com/f4h8ljrz7ns2',
    logo: '',
    cta: 'Explore Answering Service Care, LLC',
  },
  {
    slug: 'apollo-io',
    name: 'Apollo.io',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'Apollo.io is a sales and marketing platform that provides data enrichment, lead generation, and customer relationship management tools for businesses like GJH Inc.',
    excerpt: 'Apollo.io is a sales and marketing platform that provides data enrichment, lead generation, and customer relationship management tools...',
    keywords: ['gjh inc', 'apollo', 'apollo.io'],
    url: 'https://get.apollo.io/ih4fnqi383rj',
    logo: '',
    cta: 'Explore Apollo.io',
  },
  {
    slug: 'appsumo',
    name: 'AppSumo',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'AppSumo is a digital platform that offers a curated selection of software and apps at discounted prices for businesses and entrepreneurs.',
    excerpt: 'AppSumo is a digital platform that offers a curated selection of software and apps at discounted prices for businesses and entrepreneurs.',
    keywords: ['platform', 'app', 'software', 'appsumo', 'tool'],
    url: 'https://appsumo.8odi.net/c/5873369/416948/7443',
    logo: '',
    cta: 'Explore AppSumo',
  },
  {
    slug: 'arbiship',
    name: 'Arbiship',
    platform: 'Impact',
    category: 'Operations',
    description: 'Arbiship is a dropshipping automation tool that provides real-time order tracking and management features for online sellers.',
    excerpt: 'Arbiship is a dropshipping automation tool that provides real-time order tracking and management features for online sellers.',
    keywords: ['tracking', 'arbiship'],
    url: 'https://arbishipebaydropshippingautomation.sjv.io/c/5873369/392638/5709',
    logo: '',
    cta: 'Explore Arbiship',
  },
  {
    slug: 'arkuda-digital-llc-arkudadigital',
    name: 'Arkuda Digital LLC - arkudadigital',
    platform: 'Impact',
    category: 'Project Management',
    description: 'Arkuda Digital LLC\'s arkmc platform provides a project management tool for teams to organize and track tasks, timelines, and workflows in a centralized online environment.',
    excerpt: 'Arkuda Digital LLC\'s arkmc platform provides a project management tool for teams to organize and track tasks, timelines, and workflows...',
    keywords: ['arkmc', 'app', 'arkuda digital llc - arkudadigital'],
    url: 'https://arkmc.pxf.io/c/5873369/348881/5172',
    logo: '',
    cta: 'Explore Arkuda Digital LLC - arkudadigital',
  },
  {
    slug: 'aura',
    name: 'Aura',
    platform: 'PartnerStack',
    category: 'Travel & Expense',
    description: 'The Aura platform by GJH Inc provides a digital solution for automating and streamlining travel and expense management processes for businesses.',
    excerpt: 'The Aura platform by GJH Inc provides a digital solution for automating and streamlining travel and expense management processes for...',
    keywords: ['gjh inc', 'aura', 'goaura?utm_source=partners&utm_campaign={partner_key}'],
    url: 'https://try.goaura.com/45egbdjtq5mn',
    logo: '',
    cta: 'Explore Aura',
  },
  {
    slug: 'auvik',
    name: 'Auvik',
    platform: 'PartnerStack',
    category: 'IT & DevOps',
    description: 'Auvik, developed by GJH Inc., is a network management platform that automates and simplifies the monitoring and maintenance of IT infrastructure.',
    excerpt: 'Auvik, developed by GJH Inc., is a network management platform that automates and simplifies the monitoring and maintenance of IT...',
    keywords: ['auvik', 'gjh inc'],
    url: 'https://try.auvik.com/wfyaqqe2jfnc',
    logo: '',
    cta: 'Explore Auvik',
  },
  {
    slug: 'beautiful-ai',
    name: 'Beautiful.ai',
    platform: 'PartnerStack',
    category: 'Communication & Collaboration',
    description: 'Beautiful.ai is a communication and collaboration platform developed by GJH Inc that enables users to create interactive presentations and documents.',
    excerpt: 'Beautiful.ai is a communication and collaboration platform developed by GJH Inc that enables users to create interactive presentations...',
    keywords: ['gjh inc', 'beautiful.ai'],
    url: 'https://beautifulai.partnerlinks.io/n6i2hugubdp7',
    logo: '',
    cta: 'Explore Beautiful.ai',
  },
  {
    slug: 'bill',
    name: 'BILL',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'The BILL platform by GJH Inc is a financial management tool that helps businesses track and manage their invoices and payments.',
    excerpt: 'The BILL platform by GJH Inc is a financial management tool that helps businesses track and manage their invoices and payments.',
    keywords: ['gjh inc', 'bill'],
    url: 'https://referral.bill.com/p342r66k6tks',
    logo: '',
    cta: 'Explore BILL',
  },
  {
    slug: 'bitqueues',
    name: 'BitQueues',
    platform: 'Impact',
    category: 'Project Management',
    description: 'BitQueues is a project management tool that enables teams to visualize and manage complex workflows through customizable Kanban boards and queues.',
    excerpt: 'BitQueues is a project management tool that enables teams to visualize and manage complex workflows through customizable Kanban boards...',
    keywords: ['bitqueues'],
    url: 'https://bitqueues.sjv.io/c/5873369/1384272/16556',
    logo: '',
    cta: 'Explore BitQueues',
  },
  {
    slug: 'blackbox-ai',
    name: 'BLACKBOX AI',
    platform: 'PartnerStack',
    category: 'Data & Analytics',
    description: 'BlackBox AI is a data analytics platform developed by GJH Inc that provides automated machine learning model development and deployment capabilities.',
    excerpt: 'BlackBox AI is a data analytics platform developed by GJH Inc that provides automated machine learning model development and deployment...',
    keywords: ['gjh inc', 'blackbox ai', 'blackbox.ai'],
    url: 'https://blackboxai.partnerlinks.io/eisqg4n1j0iy',
    logo: '',
    cta: 'Explore BLACKBOX AI',
  },
  {
    slug: 'bluehost',
    name: 'Bluehost',
    platform: 'Impact',
    category: 'IT & DevOps',
    description: 'Bluehost is a web hosting platform that provides users with tools and services for building, launching, and managing online websites and applications.',
    excerpt: 'Bluehost is a web hosting platform that provides users with tools and services for building, launching, and managing online websites and...',
    keywords: ['tool', 'bluehost', 'platform'],
    url: 'https://bluehost.sjv.io/c/5873369/795082/11352',
    logo: '',
    cta: 'Explore Bluehost',
  },
  {
    slug: 'brand24',
    name: 'Brand24',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'Brand24 is a social media monitoring and analytics tool that tracks online conversations about brands, competitors, and industry-related topics.',
    excerpt: 'Brand24 is a social media monitoring and analytics tool that tracks online conversations about brands, competitors, and industry-related...',
    keywords: ['gjh inc', 'brand24'],
    url: 'https://try.brand24.com/5i2kp8ueee0a',
    logo: '',
    cta: 'Explore Brand24',
  },
  {
    slug: 'brevo',
    name: 'Brevo',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'Brevo is a marketing and customer relationship management platform offered by GJH Inc, also integrated with PartnerStack for seamless partnership management.',
    excerpt: 'Brevo is a marketing and customer relationship management platform offered by GJH Inc, also integrated with PartnerStack for seamless...',
    keywords: ['gjh inc', 'brevo', 'partnerstack'],
    url: 'https://get.brevo.com/2js3j3bbh0sf',
    logo: '',
    cta: 'Explore Brevo',
  },
  {
    slug: 'bytedance-pte-ltd',
    name: 'Bytedance Pte. Ltd.',
    platform: 'Impact',
    category: 'HR & Payroll',
    description: 'Bytedance Pte.',
    excerpt: 'Bytedance Pte.',
    keywords: ['bytedance pte. ltd.', 'capcut', 'tool', 'hr'],
    url: 'https://capcutaffiliateprogram.pxf.io/c/5873369/1876054/22474',
    logo: '',
    cta: 'Explore Bytedance Pte. Ltd.',
  },
  {
    slug: 'callhippo',
    name: 'CallHippo',
    platform: 'PartnerStack',
    category: 'Communication & Collaboration',
    description: 'CallHippo is a cloud-based communication platform that offers automated dialing and call tracking features for businesses, developed by GJH Inc.',
    excerpt: 'CallHippo is a cloud-based communication platform that offers automated dialing and call tracking features for businesses, developed by...',
    keywords: ['gjh inc', 'callhippo'],
    url: 'https://join.callhippo.com/mc20wch9xhcc',
    logo: '',
    cta: 'Explore CallHippo',
  },
  {
    slug: 'campaign-monitor-by-marigold',
    name: 'Campaign Monitor by Marigold',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'Campaign Monitor by Marigold is a marketing automation platform that enables users to create and manage targeted email campaigns and workflows.',
    excerpt: 'Campaign Monitor by Marigold is a marketing automation platform that enables users to create and manage targeted email campaigns and...',
    keywords: ['campaignmonitor', 'campaign monitor by marigold', 'gjh inc'],
    url: 'https://partners.campaignmonitor.com/69thf0yzysk7',
    logo: '',
    cta: 'Explore Campaign Monitor by Marigold',
  },
  {
    slug: 'capsule-and-transpond',
    name: 'Capsule and Transpond',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'The Capsule and Transpond system by GJH Inc is a customer relationship management (CRM) tool that integrates with various business applications.',
    excerpt: 'The Capsule and Transpond system by GJH Inc is a customer relationship management (CRM) tool that integrates with various business...',
    keywords: ['gjh inc', 'capsule and transpond', 'crm', 'capsulecrm'],
    url: 'https://get.capsulenow.io/e848o1v5kcof',
    logo: '',
    cta: 'Explore Capsule and Transpond',
  },
  {
    slug: 'carbon6',
    name: 'Carbon6',
    platform: 'PartnerStack',
    category: 'HR & Payroll',
    description: 'The Carbon6 platform by GJH Inc provides automated investigation and verification tools for HR and payroll teams to manage employee data securely.',
    excerpt: 'The Carbon6 platform by GJH Inc provides automated investigation and verification tools for HR and payroll teams to manage employee data...',
    keywords: ['gjh inc', 'carbon6', 'sellerinvestigators'],
    url: 'https://ps.carbon6.io/19l8i6uvqsyr',
    logo: '',
    cta: 'Explore Carbon6',
  },
  {
    slug: 'carepatron',
    name: 'Carepatron',
    platform: 'PartnerStack',
    category: 'HR & Payroll',
    description: 'CarePatron is a human capital management platform offered by GJH Inc that streamlines employee data management and benefits administration for organizations.',
    excerpt: 'CarePatron is a human capital management platform offered by GJH Inc that streamlines employee data management and benefits...',
    keywords: ['gjh inc', 'carepatron'],
    url: 'https://get.carepatron.com/cu7n7qcfnol5',
    logo: '',
    cta: 'Explore Carepatron',
  },
  {
    slug: 'cbd-for-life',
    name: 'CBD For Life',
    platform: 'Impact',
    category: 'Operations',
    description: 'The CBD For Life product line offers a range of wellness-focused products containing cannabidiol (CBD), a non-psychoactive hemp-derived compound.',
    excerpt: 'The CBD For Life product line offers a range of wellness-focused products containing cannabidiol (CBD), a non-psychoactive hemp-derived...',
    keywords: ['wellness', 'cbdforlife.us', 'cbd for life'],
    url: 'https://imp.i295461.net/c/5873369/819381/11575',
    logo: '',
    cta: 'Explore CBD For Life',
  },
  {
    slug: 'close',
    name: 'Close',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'The Close app by GJH Inc is a financial management tool that helps businesses track and manage their expenses and invoices in one place.',
    excerpt: 'The Close app by GJH Inc is a financial management tool that helps businesses track and manage their expenses and invoices in one place.',
    keywords: ['close', 'gjh inc', 'app', 'app.close'],
    url: 'https://refer.close.com/s607d2x2o1pn',
    logo: '',
    cta: 'Explore Close',
  },
  {
    slug: 'closely',
    name: 'Closely',
    platform: 'PartnerStack',
    category: 'Project Management',
    description: 'Closely is a project management tool developed by GJH Inc that helps teams track and analyze work progress in real-time.',
    excerpt: 'Closely is a project management tool developed by GJH Inc that helps teams track and analyze work progress in real-time.',
    keywords: ['closelyhq', 'gjh inc', 'closely'],
    url: 'https://get.closelyhq.com/rhfbyqvw5geq',
    logo: '',
    cta: 'Explore Closely',
  },
  {
    slug: 'cloudtalk',
    name: 'CloudTalk',
    platform: 'PartnerStack',
    category: 'Communication & Collaboration',
    description: 'CloudTalk is a cloud-based communication platform provided by GJH Inc that enables businesses to manage and streamline their customer interactions through various channels.',
    excerpt: 'CloudTalk is a cloud-based communication platform provided by GJH Inc that enables businesses to manage and streamline their customer...',
    keywords: ['gjh inc', 'cloudtalk', 'cloud'],
    url: 'https://get.cloudtalk.io/o8rn80e4its9-1xtqvk',
    logo: '',
    cta: 'Explore CloudTalk',
  },
  {
    slug: 'crowdstrike',
    name: 'CrowdStrike',
    platform: 'PartnerStack',
    category: 'Cybersecurity & Identity',
    description: 'CrowdStrike is a cloud-delivered endpoint security platform that provides threat detection and response capabilities for organizations to protect against cyber threats.',
    excerpt: 'CrowdStrike is a cloud-delivered endpoint security platform that provides threat detection and response capabilities for organizations...',
    keywords: ['crowdstrike', 'gjh inc'],
    url: 'https://crowdstrike2001.partnerlinks.io/77cf6wwvvu2w',
    logo: '',
    cta: 'Explore CrowdStrike',
  },
  {
    slug: 'databox',
    name: 'Databox',
    platform: 'PartnerStack',
    category: 'Data & Analytics',
    description: 'Databox is a data analytics platform provided by GJH Inc that helps businesses track and visualize key performance indicators in one place.',
    excerpt: 'Databox is a data analytics platform provided by GJH Inc that helps businesses track and visualize key performance indicators in one place.',
    keywords: ['gjh inc', 'databox'],
    url: 'https://join.databox.com/py8rje8lous5-5b1iq5',
    logo: '',
    cta: 'Explore Databox',
  },
  {
    slug: 'deel',
    name: 'Deel',
    platform: 'PartnerStack',
    category: 'HR & Payroll',
    description: 'Deel is a platform that streamlines global employment and payroll processes for businesses, including GJH Inc., by managing international hiring and compliance.',
    excerpt: 'Deel is a platform that streamlines global employment and payroll processes for businesses, including GJH Inc., by managing...',
    keywords: ['gjh inc', 'deel'],
    url: 'https://get.deel.com/xg56322f3p2j',
    logo: '',
    cta: 'Explore Deel',
  },
  {
    slug: 'devs-ai',
    name: 'Devs.ai',
    platform: 'PartnerStack',
    category: 'IT & DevOps',
    description: 'Devs.ai is a software development platform offered by GJH Inc., providing tools for collaborative coding and project management in an integrated environment.',
    excerpt: 'Devs.ai is a software development platform offered by GJH Inc., providing tools for collaborative coding and project management in an...',
    keywords: ['devs.ai', 'gjh inc'],
    url: 'https://join.devs.ai/9z6wbu0lvjua',
    logo: '',
    cta: 'Explore Devs.ai',
  },
  {
    slug: 'diginius',
    name: 'Diginius',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'Diginius is a financial management software solution provided by GJH Inc., offering tools for accounts payable and accounts receivable automation.',
    excerpt: 'Diginius is a financial management software solution provided by GJH Inc., offering tools for accounts payable and accounts receivable...',
    keywords: ['gjh inc', 'diginius'],
    url: 'https://get.diginius.com/jmzomg4jhkgm',
    logo: '',
    cta: 'Explore Diginius',
  },
  {
    slug: 'digitrading-hongkong-limited',
    name: 'Digitrading Hongkong Limited',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'Digitrading Hongkong Limited is a company that provides e-commerce solutions and services through its platform, connecting buyers with suppliers from various countries.',
    excerpt: 'Digitrading Hongkong Limited is a company that provides e-commerce solutions and services through its platform, connecting buyers with...',
    keywords: ['dhgate', 'digitrading hongkong limited'],
    url: 'https://dhgate.sjv.io/c/5873369/868543/12108',
    logo: '',
    cta: 'Explore Digitrading Hongkong Limited',
  },
  {
    slug: 'drip',
    name: 'Drip',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'Drip is a marketing automation platform offered by GJH Inc that enables users to create and manage automated email campaigns and workflows.',
    excerpt: 'Drip is a marketing automation platform offered by GJH Inc that enables users to create and manage automated email campaigns and workflows.',
    keywords: ['gjh inc', 'drip'],
    url: 'https://try.drip.com/4li1ih52geep',
    logo: '',
    cta: 'Explore Drip',
  },
  {
    slug: 'druva',
    name: 'Druva',
    platform: 'PartnerStack',
    category: 'Cybersecurity & Identity',
    description: 'Druva is a cloud data protection and management platform that provides backup, disaster recovery, and data governance for enterprise organizations.',
    excerpt: 'Druva is a cloud data protection and management platform that provides backup, disaster recovery, and data governance for enterprise...',
    keywords: ['gjh inc', 'druva'],
    url: 'https://druva.partnerlinks.io/63zzg2o2i0qv',
    logo: '',
    cta: 'Explore Druva',
  },
  {
    slug: 'dymocks-pty-ltd',
    name: 'Dymocks Pty Ltd',
    platform: 'Impact',
    category: 'Other',
    description: 'Dymocks Pty Ltd is a Australian retailer that operates online and in-store bookshops, offering a range of books, gifts, and other products for sale.',
    excerpt: 'Dymocks Pty Ltd is a Australian retailer that operates online and in-store bookshops, offering a range of books, gifts, and other...',
    keywords: ['dymocks pty ltd', 'dymocks.au'],
    url: 'https://dymocks-australia.pxf.io/c/5873369/1398797/16665',
    logo: '',
    cta: 'Explore Dymocks Pty Ltd',
  },
  {
    slug: 'easyship',
    name: 'Easyship',
    platform: 'Impact',
    category: 'Operations',
    description: 'Easyship is a shipping and logistics platform that provides users with tools for managing international shipments and tracking packages in real-time.',
    excerpt: 'Easyship is a shipping and logistics platform that provides users with tools for managing international shipments and tracking packages...',
    keywords: ['tracking', 'platform', 'easyship'],
    url: 'https://easyship.ilbqy6.net/c/5873369/666308/10435',
    logo: '',
    cta: 'Explore Easyship',
  },
  {
    slug: 'ebrands-global-oy',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'eBrands Global Oy offers a marketing platform that connects businesses with affiliate marketers through its Puzzler Ready Affiliate Program.',
    excerpt: 'eBrands Global Oy offers a marketing platform that connects businesses with affiliate marketers through its Puzzler Ready Affiliate Program.',
    keywords: ['ebrands global oy', 'puzzleready'],
    url: 'https://puzzlereadyaffiliateprogram.pxf.io/c/5873369/1549130/18069',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-2',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'eBrands Global Oy provides a platform for managing travel and expense reports through its website, indo-tricks-scooter.sjv.io.',
    excerpt: 'eBrands Global Oy provides a platform for managing travel and expense reports through its website, indo-tricks-scooter.sjv.io.',
    keywords: ['ebrands global oy', 'indotrickscooter'],
    url: 'https://indo-tricks-scooter.sjv.io/c/5873369/1549977/18088',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-3',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'eBrands Global Oy offers a digital marketing platform called CoachSoak that provides tools for social media management and customer relationship management (CRM) solutions.',
    excerpt: 'eBrands Global Oy offers a digital marketing platform called CoachSoak that provides tools for social media management and customer...',
    keywords: ['coachsoak', 'ebrands global oy'],
    url: 'https://coach-soak.sjv.io/c/5873369/1549982/18089',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-4',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'eBrands Global Oy offers a platform for affiliate marketing and customer relationship management through its partner program at bodyotics.sjv.io.',
    excerpt: 'eBrands Global Oy offers a platform for affiliate marketing and customer relationship management through its partner program at...',
    keywords: ['bodyotics', 'ebrands global oy'],
    url: 'https://bodyotics.sjv.io/c/5873369/1549984/18090',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-5',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'eBrands Global Oy provides a platform for digital marketing and customer relationship management solutions through its website at fofana.sjv.io.',
    excerpt: 'eBrands Global Oy provides a platform for digital marketing and customer relationship management solutions through its website at...',
    keywords: ['ebrands global oy', 'fofana'],
    url: 'https://fofana.sjv.io/c/5873369/1549986/18091',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-6',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Finance & Accounting',
    description: 'eBrands Global Oy provides financial services and solutions for businesses and individuals, with a focus on international transactions and currency exchange.',
    excerpt: 'eBrands Global Oy provides financial services and solutions for businesses and individuals, with a focus on international transactions...',
    keywords: ['penchantforpleasure', 'ebrands global oy', 'health'],
    url: 'https://penchant-for-pleasure.sjv.io/c/5873369/1582170/18358',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-7',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'eBrands Global Oy provides a digital platform for managing and optimizing marketing campaigns across multiple channels and brands through its BigBatBox solution.',
    excerpt: 'eBrands Global Oy provides a digital platform for managing and optimizing marketing campaigns across multiple channels and brands...',
    keywords: ['bigbatbox', 'ebrands global oy'],
    url: 'https://big-bat-box.pxf.io/c/5873369/1582173/18359',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-8',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'eBrands Global Oy provides digital marketing and customer relationship management services for various brands, including Viking Beard Gear\'s online presence and operations.',
    excerpt: 'eBrands Global Oy provides digital marketing and customer relationship management services for various brands, including Viking Beard...',
    keywords: ['ebrands global oy', 'vikingbeardgear'],
    url: 'https://viking-beard-gear.pxf.io/c/5873369/1582181/18360',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-9',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'eBrands Global Oy, also known as Mioeco, provides a travel and expense management platform for companies to streamline their business travel processes.',
    excerpt: 'eBrands Global Oy, also known as Mioeco, provides a travel and expense management platform for companies to streamline their business...',
    keywords: ['ebrands global oy', 'mioeco'],
    url: 'https://mioeco.sjv.io/c/5873369/1582184/18361',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-10',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'eBrands Global Oy provides a platform for managing and optimizing online brand presence through data-driven insights and marketing automation tools.',
    excerpt: 'eBrands Global Oy provides a platform for managing and optimizing online brand presence through data-driven insights and marketing...',
    keywords: ['ontaki', 'ebrands global oy'],
    url: 'https://ontaki.pxf.io/c/5873369/1597430/18533',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-11',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'HR & Payroll',
    description: 'eBrands Global Oy offers an HR and payroll management application called ASEBBO, providing tools for employee data management and administrative tasks.',
    excerpt: 'eBrands Global Oy offers an HR and payroll management application called ASEBBO, providing tools for employee data management and...',
    keywords: ['hr', 'app', 'asebbo', 'ebrands global oy'],
    url: 'https://asebbo.pxf.io/c/5873369/1597432/18534',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-12',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'HR & Payroll',
    description: 'eBrands Global Oy provides human resources and payroll management solutions for businesses, offering a range of services and tools for HR professionals.',
    excerpt: 'eBrands Global Oy provides human resources and payroll management solutions for businesses, offering a range of services and tools for...',
    keywords: ['hr', 'ebrands global oy', 'byregroup'],
    url: 'https://byre-group.pxf.io/c/5873369/1597434/18535',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-13',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'eBrands Global Oy provides a travel and expense management platform, including features such as BabyDeePSleep, for companies to streamline their business operations.',
    excerpt: 'eBrands Global Oy provides a travel and expense management platform, including features such as BabyDeePSleep, for companies to...',
    keywords: ['ebrands global oy', 'babydeepsleep'],
    url: 'https://babydeepsleep.pxf.io/c/5873369/1608958/18660',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-14',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Finance & Accounting',
    description: 'eBrands Global Oy provides a cloud-based platform for financial management and accounting solutions, offering tools for businesses to streamline their operations.',
    excerpt: 'eBrands Global Oy provides a cloud-based platform for financial management and accounting solutions, offering tools for businesses to...',
    keywords: ['cloudfield', 'ebrands global oy', 'cloud'],
    url: 'https://cloudfield.pxf.io/c/5873369/1608962/18662',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-15',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'eBrands Global Oy provides a platform for affiliate marketing and digital business solutions through its website angles90.sjv.io, offering various tools and services.',
    excerpt: 'eBrands Global Oy provides a platform for affiliate marketing and digital business solutions through its website angles90.sjv.io,...',
    keywords: ['ebrands global oy', 'angles90'],
    url: 'https://angles90.sjv.io/c/5873369/1979996/24273',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-16',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'eBrands Global Oy provides digital marketing and customer relationship management services for luxury brands, including those in the sports industry such as Lux Sports.',
    excerpt: 'eBrands Global Oy provides digital marketing and customer relationship management services for luxury brands, including those in the...',
    keywords: ['luxsports', 'ebrands global oy'],
    url: 'https://lux.sjv.io/c/5873369/1980001/24275',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-17',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'eBrands Global Oy provides a range of marketing and customer relationship management services through its platform, charlemagne.pxf.io.',
    excerpt: 'eBrands Global Oy provides a range of marketing and customer relationship management services through its platform, charlemagne.pxf.io.',
    keywords: ['charlemagne-premium', 'ebrands global oy'],
    url: 'https://charlemange.pxf.io/c/5873369/1980006/24278',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'ebrands-global-oy-18',
    name: 'eBrands Global Oy',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'eBrands Global Oy provides digital marketing services and solutions for businesses, including online presence management and customer relationship management tools.',
    excerpt: 'eBrands Global Oy provides digital marketing services and solutions for businesses, including online presence management and customer...',
    keywords: ['babysunnies', 'ebrands global oy'],
    url: 'https://babysunnies.pxf.io/c/5873369/1980009/24279',
    logo: '',
    cta: 'Explore eBrands Global Oy',
  },
  {
    slug: 'eleven-labs-inc',
    name: 'Eleven Labs Inc.',
    platform: 'PartnerStack',
    category: 'Project Management',
    description: 'Eleven Labs Inc.',
    excerpt: 'Eleven Labs Inc.',
    keywords: ['gjh inc', 'eleven labs inc.', 'elevenlabs'],
    url: 'https://try.elevenlabs.io/hqst4uvtvxhf',
    logo: '',
    cta: 'Explore Eleven Labs Inc.',
  },
  {
    slug: 'elightup-elightup',
    name: 'eLightUp - elightup',
    platform: 'Impact',
    category: 'Finance & Accounting',
    description: 'The eLightUp software provides a platform for automating and streamlining financial data management processes within organizations.',
    excerpt: 'The eLightUp software provides a platform for automating and streamlining financial data management processes within organizations.',
    keywords: ['elightup - elightup', 'elightup'],
    url: 'https://metabox.sjv.io/c/5873369/914269/12511',
    logo: '',
    cta: 'Explore eLightUp - elightup',
  },
  {
    slug: 'elightup-elightup-2',
    name: 'eLightUp - elightup',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'The eLightUp - elightup tool is a digital marketing solution that helps optimize website content and improve search engine rankings through automated SEO processes.',
    excerpt: 'The eLightUp - elightup tool is a digital marketing solution that helps optimize website content and improve search engine rankings...',
    keywords: ['elightup - elightup', 'wpslimseo'],
    url: 'https://slim-seo.sjv.io/c/5873369/1328334/16052',
    logo: '',
    cta: 'Explore eLightUp - elightup',
  },
  {
    slug: 'emergent-labs-inc',
    name: 'Emergent Labs Inc',
    platform: 'PartnerStack',
    category: 'Project Management',
    description: 'Emergent Labs Inc offers a project management application available at get.emergent.sh and app.emergent.sh, providing tools for task organization and team collaboration.',
    excerpt: 'Emergent Labs Inc offers a project management application available at get.emergent.sh and app.emergent.sh, providing tools for task...',
    keywords: ['gjh inc', 'app', 'app.emergent.sh', 'emergent labs inc'],
    url: 'https://get.emergent.sh/l84z4l1mjlju',
    logo: '',
    cta: 'Explore Emergent Labs Inc',
  },
  {
    slug: 'encounters-pte-ltd',
    name: 'Encounters Pte Ltd',
    platform: 'Impact',
    category: 'Project Management',
    description: 'Encounters Pte Ltd offers a project management platform called Pelago that enables teams to plan and track projects through a centralized online workspace.',
    excerpt: 'Encounters Pte Ltd offers a project management platform called Pelago that enables teams to plan and track projects through a...',
    keywords: ['pelago', 'platform', 'encounters pte ltd'],
    url: 'https://pelago.pxf.io/c/5873369/1851844/22181',
    logo: '',
    cta: 'Explore Encounters Pte Ltd',
  },
  {
    slug: 'expertex',
    name: 'ExpertEx',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'ExpertEx by try.expertex.ai is a cloud-based financial management platform that automates and streamlines accounting processes for businesses like GJH Inc.',
    excerpt: 'ExpertEx by try.expertex.ai is a cloud-based financial management platform that automates and streamlines accounting processes for...',
    keywords: ['gjh inc', 'expertex.ai', 'expertex'],
    url: 'https://try.expertex.ai/czdqv0tieydb',
    logo: '',
    cta: 'Explore ExpertEx',
  },
  {
    slug: 'eyeson-team',
    name: 'eyeson.team',
    platform: 'Impact',
    category: 'Communication & Collaboration',
    description: 'Eyeson.team is a cloud-based video conferencing and collaboration platform that enables remote teams to communicate and share content in real-time.',
    excerpt: 'Eyeson.team is a cloud-based video conferencing and collaboration platform that enables remote teams to communicate and share content in...',
    keywords: ['eyeson.team'],
    url: 'https://eyeson.sjv.io/c/5873369/559443/9315',
    logo: '',
    cta: 'Explore eyeson.team',
  },
  {
    slug: 'flippa-com',
    name: 'Flippa.com',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'Flippa.com is a marketplace where buyers and sellers can connect to buy and sell online businesses, domains, and digital assets.',
    excerpt: 'Flippa.com is a marketplace where buyers and sellers can connect to buy and sell online businesses, domains, and digital assets.',
    keywords: ['gjh inc', 'flippa', 'flippa.com'],
    url: 'https://referral.flippa.com/zawddwgz8yno-5i76g',
    logo: '',
    cta: 'Explore Flippa.com',
  },
  {
    slug: 'folk',
    name: 'folk',
    platform: 'PartnerStack',
    category: 'Travel & Expense',
    description: 'Folk is a travel and expense management platform offered by GJH Inc., accessible through the try.folk.app website.',
    excerpt: 'Folk is a travel and expense management platform offered by GJH Inc., accessible through the try.folk.app website.',
    keywords: ['gjh inc', 'folk', 'app', 'folk.app'],
    url: 'https://try.folk.app/2adrxyae7k0c',
    logo: '',
    cta: 'Explore folk',
  },
  {
    slug: 'foxit',
    name: 'Foxit',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'Foxit is a document management and processing software used by GJH Inc for financial and accounting tasks, such as electronic signature capture and document review.',
    excerpt: 'Foxit is a document management and processing software used by GJH Inc for financial and accounting tasks, such as electronic signature...',
    keywords: ['gjh inc', 'foxit'],
    url: 'https://partnerstack.foxit.com/2duzrmm6vjb2',
    logo: '',
    cta: 'Explore Foxit',
  },
  {
    slug: 'freshchat',
    name: 'Freshchat',
    platform: 'PartnerStack',
    category: 'Communication & Collaboration',
    description: 'Freshchat is a customer messaging platform that integrates with Freshdesk and other tools to provide omnichannel support and engagement capabilities.',
    excerpt: 'Freshchat is a customer messaging platform that integrates with Freshdesk and other tools to provide omnichannel support and engagement...',
    keywords: ['freshchat', 'gjh inc', 'freshdesk'],
    url: 'https://affiliatepartner-freshchat.freshworks.com/g3v2y009yss8',
    logo: '',
    cta: 'Explore Freshchat',
  },
  {
    slug: 'freshdesk-by-freshworks',
    name: 'Freshdesk by Freshworks',
    platform: 'PartnerStack',
    category: 'Communication & Collaboration',
    description: 'Freshdesk by Freshworks is a cloud-based customer service software that enables businesses to manage and track support requests from a single platform.',
    excerpt: 'Freshdesk by Freshworks is a cloud-based customer service software that enables businesses to manage and track support requests from a...',
    keywords: ['gjh inc', 'freshdesk by freshworks', 'freshworks'],
    url: 'https://affiliatepartner.freshdesk.com/0iknoijpfz42',
    logo: '',
    cta: 'Explore Freshdesk by Freshworks',
  },
  {
    slug: 'freshservice-by-freshworks',
    name: 'Freshservice by Freshworks',
    platform: 'PartnerStack',
    category: 'Project Management',
    description: 'Freshservice by Freshworks is a cloud-based IT service management platform that helps organizations manage and track their IT projects and services.',
    excerpt: 'Freshservice by Freshworks is a cloud-based IT service management platform that helps organizations manage and track their IT projects...',
    keywords: ['gjh inc', 'freshservice by freshworks', 'freshworks'],
    url: 'https://affiliatepartner-freshservice.freshworks.com/qxkf6wvm0ab6',
    logo: '',
    cta: 'Explore Freshservice by Freshworks',
  },
  {
    slug: 'gamma',
    name: 'Gamma',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'The Gamma application from GJH Inc is a financial management tool that provides users with data analytics and reporting capabilities for their organizations.',
    excerpt: 'The Gamma application from GJH Inc is a financial management tool that provides users with data analytics and reporting capabilities for...',
    keywords: ['gamma.app', 'gjh inc', 'app', 'gamma'],
    url: 'https://try.gamma.app/s0pyubb6gue0',
    logo: '',
    cta: 'Explore Gamma',
  },
  {
    slug: 'getresponse-services-inc',
    name: 'GetResponse Services Inc.',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'GetResponse Services Inc.',
    excerpt: 'GetResponse Services Inc.',
    keywords: ['gjh inc', 'getresponse services inc.', 'wwww.getresponse'],
    url: 'https://try.getresponsetoday.com/92e3zsxnzj9w-xlkg1t',
    logo: '',
    cta: 'Explore GetResponse Services Inc.',
  },
  {
    slug: 'gettrusted',
    name: 'GetTrusted',
    platform: 'PartnerStack',
    category: 'Cybersecurity & Identity',
    description: 'GetTrusted is a cybersecurity and identity management platform offered by GJH Inc that provides secure authentication and verification services for individuals and organizations.',
    excerpt: 'GetTrusted is a cybersecurity and identity management platform offered by GJH Inc that provides secure authentication and verification...',
    keywords: ['gjh inc', 'gettrusted'],
    url: 'https://start.gettrusted.io/mx8givgo6a6h',
    logo: '',
    cta: 'Explore GetTrusted',
  },
  {
    slug: 'golf-partner',
    name: 'GOLF Partner',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'The GOLF Partner platform provides a travel and expense management solution for golf-related trips, offering features such as itinerary planning and expense tracking.',
    excerpt: 'The GOLF Partner platform provides a travel and expense management solution for golf-related trips, offering features such as itinerary...',
    keywords: ['golf partner', 'golfpartnerusa'],
    url: 'https://golfpartner.sjv.io/c/5873369/1433527/17026',
    logo: '',
    cta: 'Explore GOLF Partner',
  },
  {
    slug: 'hangzhou-tangpushi-home-products-co-ltd',
    name: 'Hangzhou Tangpushi Home Products Co., Ltd',
    platform: 'Impact',
    category: 'Operations',
    description: 'Hangzhou Tangpushi Home Products Co., Ltd specializes in designing and manufacturing window treatments, including curtains and blinds, for residential and commercial use.',
    excerpt: 'Hangzhou Tangpushi Home Products Co., Ltd specializes in designing and manufacturing window treatments, including curtains and blinds,...',
    keywords: ['twopagescurtains', 'hangzhou tangpushi home products co., ltd'],
    url: 'https://twopages.pxf.io/c/5873369/1597849/18544',
    logo: '',
    cta: 'Explore Hangzhou Tangpushi Home Products Co., Ltd',
  },
  {
    slug: 'hive',
    name: 'Hive',
    platform: 'PartnerStack',
    category: 'Project Management',
    description: 'Hive is a project management tool developed by GJH Inc., designed to help teams organize and track tasks, projects, and workflows in a centralized platform.',
    excerpt: 'Hive is a project management tool developed by GJH Inc., designed to help teams organize and track tasks, projects, and workflows in a...',
    keywords: ['hive', 'gjh inc'],
    url: 'https://get.hive.com/4nww91y2gsr7',
    logo: '',
    cta: 'Explore Hive',
  },
  {
    slug: 'hk-petrus-international-trade-co-limited',
    name: 'HK Petrus International Trade Co., Limited',
    platform: 'Impact',
    category: 'Operations',
    description: 'HK Petrus International Trade Co., Limited is a company that specializes in providing lighting solutions and related products through its online platform, wherelight.pxf.io.',
    excerpt: 'HK Petrus International Trade Co., Limited is a company that specializes in providing lighting solutions and related products through...',
    keywords: ['wherelight', 'hk petrus international trade co., limited'],
    url: 'https://wherelight.pxf.io/c/5873369/1416907/16860',
    logo: '',
    cta: 'Explore HK Petrus International Trade Co., Limited',
  },
  {
    slug: 'hong-kong-yuzhou-information-technology-co-limited',
    name: 'Hong Kong Yuzhou Information Technology Co.,Limited',
    platform: 'Impact',
    category: 'Project Management',
    description: 'Hong Kong Yuzhou Information Technology Co., Limited offers project management software solutions through its ModLily platform, providing tools for task organization and team collaboration.',
    excerpt: 'Hong Kong Yuzhou Information Technology Co., Limited offers project management software solutions through its ModLily platform,...',
    keywords: ['hong kong yuzhou information technology co.,limited', 'modlily'],
    url: 'https://modlily.sjv.io/c/5873369/1436026/17059',
    logo: '',
    cta: 'Explore Hong Kong Yuzhou Information Technology Co.,Limited',
  },
  {
    slug: 'increff',
    name: 'Increff',
    platform: 'PartnerStack',
    category: 'Operations',
    description: 'Increff is a cloud-based platform that helps businesses like GJH Inc streamline their operations by automating inventory management and supply chain processes.',
    excerpt: 'Increff is a cloud-based platform that helps businesses like GJH Inc streamline their operations by automating inventory management and...',
    keywords: ['gjh inc', 'increff'],
    url: 'https://partners.increff.com/5vw7tdwycvs7',
    logo: '',
    cta: 'Explore Increff',
  },
  {
    slug: 'innovative-extracts',
    name: 'Innovative Extracts',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'Innovative Extracts offers a range of CBD products and solutions for businesses, providing customizable formulations and branding options.',
    excerpt: 'Innovative Extracts offers a range of CBD products and solutions for businesses, providing customizable formulations and branding options.',
    keywords: ['innovative extracts', 'ie-cbd'],
    url: 'https://innovative-extracts.pxf.io/c/5873369/1171993/14789',
    logo: '',
    cta: 'Explore Innovative Extracts',
  },
  {
    slug: 'intellistack',
    name: 'Intellistack',
    platform: 'PartnerStack',
    category: 'Project Management',
    description: 'Intellistack is a project management tool developed by GJH Inc that integrates with FormStack to streamline workflow and data collection processes.',
    excerpt: 'Intellistack is a project management tool developed by GJH Inc that integrates with FormStack to streamline workflow and data collection...',
    keywords: ['gjh inc', 'formstack', 'intellistack'],
    url: 'https://intellistack.partnerlinks.io/z8h06xjsb26w',
    logo: '',
    cta: 'Explore Intellistack',
  },
  {
    slug: 'international-open-academy',
    name: 'International Open Academy',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'The International Open Academy is an online learning platform offering courses and training programs in marketing, business, and related fields.',
    excerpt: 'The International Open Academy is an online learning platform offering courses and training programs in marketing, business, and related...',
    keywords: ['internationalopenacademy', 'international open academy'],
    url: 'https://ioa.pxf.io/c/5873369/955476/12764',
    logo: '',
    cta: 'Explore International Open Academy',
  },
  {
    slug: 'jackery',
    name: 'Jackery',
    platform: 'Impact',
    category: 'Operations',
    description: 'The Jackery brand offers portable power solutions, including solar generators and power stations for outdoor and emergency use applications.',
    excerpt: 'The Jackery brand offers portable power solutions, including solar generators and power stations for outdoor and emergency use applications.',
    keywords: ['jackery', 'nl.jackery'],
    url: 'https://itjackery.pxf.io/c/5873369/1762660/20686',
    logo: '',
    cta: 'Explore Jackery',
  },
  {
    slug: 'kailo',
    name: 'Kailo',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'The Kailo platform is a travel and expense management tool that helps users track and organize business-related trips and expenses.',
    excerpt: 'The Kailo platform is a travel and expense management tool that helps users track and organize business-related trips and expenses.',
    keywords: ['kailo', 'gokailo'],
    url: 'https://kailo.sjv.io/c/5873369/1354101/16311?utm_campaign=xca1&utm_medium=xca1&utm_source=xca1354101',
    logo: '',
    cta: 'Explore Kailo',
  },
  {
    slug: 'kinetic-innovative-staffing',
    name: 'Kinetic Innovative Staffing',
    platform: 'PartnerStack',
    category: 'HR & Payroll',
    description: 'Kinetic Innovative Staffing, a division of GJH Inc., provides temporary and permanent staffing solutions for businesses in various industries.',
    excerpt: 'Kinetic Innovative Staffing, a division of GJH Inc., provides temporary and permanent staffing solutions for businesses in various...',
    keywords: ['kineticstaff', 'gjh inc', 'kinetic innovative staffing'],
    url: 'https://partners.kineticstaff.com/kwq8jhohggy2',
    logo: '',
    cta: 'Explore Kinetic Innovative Staffing',
  },
  {
    slug: 'krispcall-communications-inc',
    name: 'KrispCall Communications Inc.',
    platform: 'PartnerStack',
    category: 'Communication & Collaboration',
    description: 'KrispCall Communications Inc.',
    excerpt: 'KrispCall Communications Inc.',
    keywords: ['gjh inc', 'krispcall', 'krispcall communications inc.'],
    url: 'https://try.krispcall.com/fuxdqo6wm45n',
    logo: '',
    cta: 'Explore KrispCall Communications Inc.',
  },
  {
    slug: 'landbot',
    name: 'Landbot',
    platform: 'PartnerStack',
    category: 'Communication & Collaboration',
    description: 'Landbot is a conversational marketing platform developed by GJH Inc that enables businesses to create and manage chatbots for customer interactions.',
    excerpt: 'Landbot is a conversational marketing platform developed by GJH Inc that enables businesses to create and manage chatbots for customer...',
    keywords: ['gjh inc', 'landbot'],
    url: 'https://get.landbotlab.com/oq17u7ynjeue',
    logo: '',
    cta: 'Explore Landbot',
  },
  {
    slug: 'learnworlds-top-user-rated-online-course-platform-lms',
    name: 'LearnWorlds - Top User-rated  Online Course Platform & LMS',
    platform: 'PartnerStack',
    category: 'Project Management',
    description: 'LearnWorlds is a cloud-based Learning Management System (LMS) that enables users to create, sell, and manage online courses and educational content.',
    excerpt: 'LearnWorlds is a cloud-based Learning Management System (LMS) that enables users to create, sell, and manage online courses and...',
    keywords: ['learnworlds - top user-rated  online course platform & lms', 'gjh inc', 'learnworlds'],
    url: 'https://get.learnworlds.com/iwvpt3ou5fye',
    logo: '',
    cta: 'Explore LearnWorlds - Top User-rated  Online Course Platform & LMS',
  },
  {
    slug: 'lenovo-india',
    name: 'Lenovo India',
    platform: 'Impact',
    category: 'Other',
    description: 'Lenovo India is a subsidiary of Lenovo Group Limited that provides technology products and services in the Indian market through its online platform.',
    excerpt: 'Lenovo India is a subsidiary of Lenovo Group Limited that provides technology products and services in the Indian market through its...',
    keywords: ['lenovo india', 'lenovo'],
    url: 'https://lenovo-in.zlvv.net/c/5873369/584269/9634',
    logo: '',
    cta: 'Explore Lenovo India',
  },
  {
    slug: 'lindy',
    name: 'Lindy',
    platform: 'PartnerStack',
    category: 'Communication & Collaboration',
    description: 'Lindy is a communication and collaboration platform that enables teams to integrate multiple messaging channels into a single interface for streamlined communication.',
    excerpt: 'Lindy is a communication and collaboration platform that enables teams to integrate multiple messaging channels into a single interface...',
    keywords: ['gjh inc', 'lindy', 'chat.lindy.ai'],
    url: 'https://try.lindy.ai/kg7l0ul5zemx',
    logo: '',
    cta: 'Explore Lindy',
  },
  {
    slug: 'mail-backup-x-inventpure',
    name: 'Mail Backup X - inventpure',
    platform: 'Impact',
    category: 'Communication & Collaboration',
    description: 'Mail Backup X by InventPure is a software tool designed for backing up and managing email data from various email clients and services.',
    excerpt: 'Mail Backup X by InventPure is a software tool designed for backing up and managing email data from various email clients and services.',
    keywords: ['mail backup x - inventpure', 'mailbackupx'],
    url: 'https://inventpure.pxf.io/c/5873369/869076/12121',
    logo: '',
    cta: 'Explore Mail Backup X - inventpure',
  },
  {
    slug: 'marketxls-limited-technitya',
    name: 'marketXLS Limited - technitya',
    platform: 'Impact',
    category: 'Finance & Accounting',
    description: 'MarketXLS Limited\'s Technitya is a financial analysis and data management tool that provides users with features for importing, processing, and exporting spreadsheet data.',
    excerpt: 'MarketXLS Limited\'s Technitya is a financial analysis and data management tool that provides users with features for importing,...',
    keywords: ['app', 'software', 'marketxls limited - technitya', 'tool', 'marketxls'],
    url: 'https://marketxls.pxf.io/c/5873369/346120/5139',
    logo: '',
    cta: 'Explore marketXLS Limited - technitya',
  },
  {
    slug: 'mongodb',
    name: 'MongoDB',
    platform: 'PartnerStack',
    category: 'Data & Analytics',
    description: 'MongoDB is a cross-platform, document-oriented database software developed by MongoDB Inc., used for storing and managing large amounts of semi-structured data.',
    excerpt: 'MongoDB is a cross-platform, document-oriented database software developed by MongoDB Inc., used for storing and managing large amounts...',
    keywords: ['gjh inc', 'mongodb'],
    url: 'https://mongodb.partnerlinks.io/fvfld1r9i7px',
    logo: '',
    cta: 'Explore MongoDB',
  },
  {
    slug: 'mrpeasy',
    name: 'MRPeasy',
    platform: 'PartnerStack',
    category: 'Operations',
    description: 'MRPeasy is a cloud-based manufacturing operations management system developed by GJH Inc., providing tools for production planning and control.',
    excerpt: 'MRPeasy is a cloud-based manufacturing operations management system developed by GJH Inc., providing tools for production planning and...',
    keywords: ['gjh inc', 'app', 'mrpeasy', 'app.mrpeasy'],
    url: 'https://try.mrpeasy.com/oz60w9tskf5j',
    logo: '',
    cta: 'Explore MRPeasy',
  },
  {
    slug: 'natural-cycles',
    name: 'Natural Cycles',
    platform: 'Impact',
    category: 'Other',
    description: 'The Natural Cycles app is a fertility tracking tool that uses algorithms and user input to predict menstrual cycles and fertility windows.',
    excerpt: 'The Natural Cycles app is a fertility tracking tool that uses algorithms and user input to predict menstrual cycles and fertility windows.',
    keywords: ['natural cycles', 'app', 'health', 'naturalcycles'],
    url: 'https://natural-cycles.sjv.io/c/5873369/1530057/17885',
    logo: '',
    cta: 'Explore Natural Cycles',
  },
  {
    slug: 'naturecan',
    name: 'Naturecan',
    platform: 'Impact',
    category: 'HR & Payroll',
    description: 'Naturecan is a German-based provider of human resources and payroll software solutions for businesses, offering tools for employee management and administration.',
    excerpt: 'Naturecan is a German-based provider of human resources and payroll software solutions for businesses, offering tools for employee...',
    keywords: ['naturecan.de', 'naturecan'],
    url: 'https://naturecan-de.sjv.io/c/5873369/1009676/13215',
    logo: '',
    cta: 'Explore Naturecan',
  },
  {
    slug: 'navan',
    name: 'Navan',
    platform: 'PartnerStack',
    category: 'Travel & Expense',
    description: 'Navan is a travel and expense management platform developed by GJH Inc., providing tools for tracking and automating business-related expenses.',
    excerpt: 'Navan is a travel and expense management platform developed by GJH Inc., providing tools for tracking and automating business-related...',
    keywords: ['gjh inc', 'navan'],
    url: 'https://get.navan.com/ncyi79mkxwkr',
    logo: '',
    cta: 'Explore Navan',
  },
  {
    slug: 'nayax',
    name: 'Nayax',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'Nayax is a cloud-based platform that provides businesses with a suite of tools for managing and optimizing their customer relationships and marketing efforts.',
    excerpt: 'Nayax is a cloud-based platform that provides businesses with a suite of tools for managing and optimizing their customer relationships...',
    keywords: ['marketing', 'nayax'],
    url: 'https://nayax.pxf.io/c/5873369/1236849/15225',
    logo: '',
    cta: 'Explore Nayax',
  },
  {
    slug: 'neo-media-world-a-division-of-wpp-marketing-communications-m',
    name: 'Neo Media World (a division of WPP Marketing Communications (M)',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'Neo Media World, a division of WPP Marketing Communications (M), provides digital marketing services for clients in the healthcare and travel sectors.',
    excerpt: 'Neo Media World, a division of WPP Marketing Communications (M), provides digital marketing services for clients in the healthcare and...',
    keywords: ['malaysiahealthcare.org', 'neo media world (a division of wpp marketing communications (m)', 'health'],
    url: 'https://malaysia-healthcare-travel-council.pxf.io/c/5873369/1469850/17382',
    logo: '',
    cta: 'Explore Neo Media World (a division of WPP Marketing Communications (M)',
  },
  {
    slug: 'nextiva',
    name: 'Nextiva',
    platform: 'PartnerStack',
    category: 'Communication & Collaboration',
    description: 'Nextiva is a cloud-based communication and collaboration platform that provides businesses with tools for unified communications, customer engagement, and team management.',
    excerpt: 'Nextiva is a cloud-based communication and collaboration platform that provides businesses with tools for unified communications,...',
    keywords: ['gjh inc', 'nextiva'],
    url: 'https://trial.nextiva.com/8psjrxle9oht',
    logo: '',
    cta: 'Explore Nextiva',
  },
  {
    slug: 'norton-small-business',
    name: 'Norton Small Business',
    platform: 'PartnerStack',
    category: 'Cybersecurity & Identity',
    description: 'The Norton Small Business solution provides comprehensive cybersecurity protection for small businesses and their employees against various online threats.',
    excerpt: 'The Norton Small Business solution provides comprehensive cybersecurity protection for small businesses and their employees against...',
    keywords: ['norton small business', 'gjh inc', 'buy.norton'],
    url: 'https://norton.partnerlinks.io/ag3qx2kaf3sq',
    logo: '',
    cta: 'Explore Norton Small Business',
  },
  {
    slug: 'notjustagency',
    name: 'notjustagency',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'Notjustagency is a marketing and customer relationship management platform that offers tools for businesses to streamline their online presence and interactions with customers.',
    excerpt: 'Notjustagency is a marketing and customer relationship management platform that offers tools for businesses to streamline their online...',
    keywords: ['onemilebike', 'notjustagency'],
    url: 'https://onemilebike.sjv.io/c/5873369/1787045/21135',
    logo: '',
    cta: 'Explore notjustagency',
  },
  {
    slug: 'oneplus-technology-shenzhen-co-ltd',
    name: 'OnePlus Technology (Shenzhen) Co., Ltd.',
    platform: 'Impact',
    category: 'Operations',
    description: 'OnePlus Technology (Shenzhen) Co., Ltd.',
    excerpt: 'OnePlus Technology (Shenzhen) Co., Ltd.',
    keywords: ['tracking', 'oneplus technology (shenzhen) co., ltd.', 'oneplus'],
    url: 'https://oneplusfr.sjv.io/c/5873369/1103247/14044',
    logo: '',
    cta: 'Explore OnePlus Technology (Shenzhen) Co., Ltd.',
  },
  {
    slug: 'optery',
    name: 'Optery',
    platform: 'PartnerStack',
    category: 'Data & Analytics',
    description: 'Optery is a data analytics platform developed by GJH Inc that helps businesses collect and manage web scraping data from various sources.',
    excerpt: 'Optery is a data analytics platform developed by GJH Inc that helps businesses collect and manage web scraping data from various sources.',
    keywords: ['gjh inc', 'optery'],
    url: 'https://get.optery.com/16firnt58jbl',
    logo: '',
    cta: 'Explore Optery',
  },
  {
    slug: 'pandadoc',
    name: 'PandaDoc',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'PandaDoc is a digital document management platform that enables businesses to create, send, and track electronic documents, such as contracts and proposals.',
    excerpt: 'PandaDoc is a digital document management platform that enables businesses to create, send, and track electronic documents, such as...',
    keywords: ['gjh inc', 'pandadoc'],
    url: 'https://pandadoc.partnerlinks.io/v6mrkt3d4oi3',
    logo: '',
    cta: 'Explore PandaDoc',
  },
  {
    slug: 'passpack',
    name: 'Passpack',
    platform: 'PartnerStack',
    category: 'HR & Payroll',
    description: 'Passpack is a cloud-based password management and identity access solution offered by GJH Inc, designed for organizations to securely store and share sensitive information.',
    excerpt: 'Passpack is a cloud-based password management and identity access solution offered by GJH Inc, designed for organizations to securely...',
    keywords: ['gjh inc', 'passpack'],
    url: 'https://try.passpack.com/71rk4nf3o7ak',
    logo: '',
    cta: 'Explore Passpack',
  },
  {
    slug: 'plesk',
    name: 'Plesk',
    platform: 'PartnerStack',
    category: 'IT & DevOps',
    description: 'Plesk is a web hosting control panel developed by Plesk Inc., providing tools for server management and website administration.',
    excerpt: 'Plesk is a web hosting control panel developed by Plesk Inc., providing tools for server management and website administration.',
    keywords: ['gjh inc', 'plesk'],
    url: 'https://try.plesk.com/x25do7zc7m6j',
    logo: '',
    cta: 'Explore Plesk',
  },
  {
    slug: 'points',
    name: 'Points',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'United ElfM Points is a digital platform that allows users to track and manage their travel-related expenses and rewards in one place.',
    excerpt: 'United ElfM Points is a digital platform that allows users to track and manage their travel-related expenses and rewards in one place.',
    keywords: ['points'],
    url: 'https://united.elfm.net/c/5873369/302886/4704',
    logo: '',
    cta: 'Explore Points',
  },
  {
    slug: 'points-2',
    name: 'Points',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'The Points platform allows users to track and manage their travel rewards points across multiple loyalty programs in one place.',
    excerpt: 'The Points platform allows users to track and manage their travel rewards points across multiple loyalty programs in one place.',
    keywords: ['points'],
    url: 'https://swa.eyjo.net/c/5873369/302888/4705',
    logo: '',
    cta: 'Explore Points',
  },
  {
    slug: 'points-3',
    name: 'Points',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'The Points platform is a travel and expense management tool that helps users track and redeem loyalty program points and rewards.',
    excerpt: 'The Points platform is a travel and expense management tool that helps users track and redeem loyalty program points and rewards.',
    keywords: ['points'],
    url: 'https://alaska.gqco.net/c/5873369/302892/4707',
    logo: '',
    cta: 'Explore Points',
  },
  {
    slug: 'points-4',
    name: 'Points',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'The Points platform allows users to manage and redeem loyalty points across various travel programs in a centralized online environment.',
    excerpt: 'The Points platform allows users to manage and redeem loyalty points across various travel programs in a centralized online environment.',
    keywords: ['points'],
    url: 'https://ihg.hmxg.net/c/5873369/310617/4797',
    logo: '',
    cta: 'Explore Points',
  },
  {
    slug: 'points-5',
    name: 'Points',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'The Hilton Points system allows members to earn and redeem points for stays at participating hotels and resorts worldwide.',
    excerpt: 'The Hilton Points system allows members to earn and redeem points for stays at participating hotels and resorts worldwide.',
    keywords: ['points'],
    url: 'https://hilton.ijrn.net/c/5873369/314255/4823',
    logo: '',
    cta: 'Explore Points',
  },
  {
    slug: 'points-6',
    name: 'Points',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'The Points program is a rewards system that allows users to earn and redeem points for travel and other experiences through various partnerships.',
    excerpt: 'The Points program is a rewards system that allows users to earn and redeem points for travel and other experiences through various...',
    keywords: ['points'],
    url: 'https://hyatt.jewn.net/c/5873369/319067/4882',
    logo: '',
    cta: 'Explore Points',
  },
  {
    slug: 'points-7',
    name: 'Points',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'The Points platform is a travel and expense management tool that helps users track and redeem loyalty rewards from various airlines and partners.',
    excerpt: 'The Points platform is a travel and expense management tool that helps users track and redeem loyalty rewards from various airlines and...',
    keywords: ['points'],
    url: 'https://jetblue.jyeh.net/c/5873369/319069/4883',
    logo: '',
    cta: 'Explore Points',
  },
  {
    slug: 'points-8',
    name: 'Points',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'The Points platform is a travel and expense management tool that helps companies track and manage employee expenses, including tracking points or rewards.',
    excerpt: 'The Points platform is a travel and expense management tool that helps companies track and manage employee expenses, including tracking...',
    keywords: ['points'],
    url: 'https://choice.mtko.net/c/5873369/319073/4885',
    logo: '',
    cta: 'Explore Points',
  },
  {
    slug: 'points-9',
    name: 'Points',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'The Points platform provides a centralized system for tracking and managing employee expenses, including mileage and other travel-related costs.',
    excerpt: 'The Points platform provides a centralized system for tracking and managing employee expenses, including mileage and other...',
    keywords: ['points'],
    url: 'https://afklm.tcux.net/c/5873369/321349/4926',
    logo: '',
    cta: 'Explore Points',
  },
  {
    slug: 'points-10',
    name: 'Points',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'The Points platform is a travel and expense management tool that helps users track and redeem loyalty points across various programs.',
    excerpt: 'The Points platform is a travel and expense management tool that helps users track and redeem loyalty points across various programs.',
    keywords: ['points'],
    url: 'https://marriott.pxf.io/c/5873369/321373/4937',
    logo: '',
    cta: 'Explore Points',
  },
  {
    slug: 'points-11',
    name: 'Points',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'The Points service allows users to manage and redeem their Copa Airlines loyalty program rewards, including accumulated miles and points.',
    excerpt: 'The Points service allows users to manage and redeem their Copa Airlines loyalty program rewards, including accumulated miles and points.',
    keywords: ['copaair', 'points'],
    url: 'https://copa.sjv.io/c/5873369/343960/5123',
    logo: '',
    cta: 'Explore Points',
  },
  {
    slug: 'points-12',
    name: 'Points',
    platform: 'Impact',
    category: 'Finance & Accounting',
    description: 'The Points platform is a digital rewards and loyalty management system for businesses to track and redeem customer points.',
    excerpt: 'The Points platform is a digital rewards and loyalty management system for businesses to track and redeem customer points.',
    keywords: ['storefront.points', 'points'],
    url: 'https://etihad.vkuz.net/c/5873369/343962/5124',
    logo: '',
    cta: 'Explore Points',
  },
  {
    slug: 'points-13',
    name: 'Points',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'Qatar Points is a digital platform that enables users to track and manage their loyalty points across various travel and expense programs.',
    excerpt: 'Qatar Points is a digital platform that enables users to track and manage their loyalty points across various travel and expense programs.',
    keywords: ['points'],
    url: 'https://qatarpts.pxf.io/c/5873369/840242/11750',
    logo: '',
    cta: 'Explore Points',
  },
  {
    slug: 'puzzle-io',
    name: 'Puzzle.io',
    platform: 'PartnerStack',
    category: 'Project Management',
    description: 'Puzzle.io is a project management tool offered by GJH Inc that enables users to organize and track tasks through interactive digital puzzles.',
    excerpt: 'Puzzle.io is a project management tool offered by GJH Inc that enables users to organize and track tasks through interactive digital...',
    keywords: ['gjh inc', 'puzzle.io', 'puzzle'],
    url: 'https://puzzleio.partnerlinks.io/cwzcbbmhmla9',
    logo: '',
    cta: 'Explore Puzzle.io',
  },
  {
    slug: 'r-e-cost-seg',
    name: 'R.E. Cost Seg',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'The R.E.',
    excerpt: 'The R.E.',
    keywords: ['recostseg', 'gjh inc', 'r.e. cost seg'],
    url: 'https://get.recostseg.com/etath679aqbl',
    logo: '',
    cta: 'Explore R.E. Cost Seg',
  },
  {
    slug: 'reclaim-ai',
    name: 'Reclaim.ai',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'Reclaim.ai is a software solution that automates accounts payable and invoice processing for businesses, such as GJH Inc., by streamlining financial workflows.',
    excerpt: 'Reclaim.ai is a software solution that automates accounts payable and invoice processing for businesses, such as GJH Inc., by...',
    keywords: ['gjh inc', 'reclaim.ai', 'reclaim.ai?utm_term=ps_{partner_key}&utm_campaign=partnerstack'],
    url: 'https://go.reclaim.ai/24aebp5w016k',
    logo: '',
    cta: 'Explore Reclaim.ai',
  },
  {
    slug: 'sitesgpt-com',
    name: 'SitesGPT.com',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'SitesGPT.com is a website management platform provided by GJH Inc that offers tools for creating and managing online presence and customer relationships.',
    excerpt: 'SitesGPT.com is a website management platform provided by GJH Inc that offers tools for creating and managing online presence and...',
    keywords: ['sitesgpt.com', 'gjh inc', 'sitesgpt'],
    url: 'https://affiliate.sitesgpt.com/422edfl2rth5',
    logo: '',
    cta: 'Explore SitesGPT.com',
  },
  {
    slug: 'skylum-software',
    name: 'Skylum Software',
    platform: 'Impact',
    category: 'Marketing & CRM',
    description: 'Skylum Software offers a suite of creative apps, including Luminar and Skylum App, for photographers and content creators to enhance their images.',
    excerpt: 'Skylum Software offers a suite of creative apps, including Luminar and Skylum App, for photographers and content creators to enhance...',
    keywords: ['skylum software', 'marketing', 'app', 'imgmiapp'],
    url: 'https://imgmi.pxf.io/c/5873369/1472460/17409',
    logo: '',
    cta: 'Explore Skylum Software',
  },
  {
    slug: 'smartli',
    name: 'Smartli',
    platform: 'PartnerStack',
    category: 'Project Management',
    description: 'Smartli is a project management tool developed by GJH Inc that provides features for task assignment and tracking within a collaborative online environment.',
    excerpt: 'Smartli is a project management tool developed by GJH Inc that provides features for task assignment and tracking within a collaborative...',
    keywords: ['gjh inc', 'smartli', 'smartli.ai'],
    url: 'https://smartli.partnerlinks.io/6tcu2al1tz48',
    logo: '',
    cta: 'Explore Smartli',
  },
  {
    slug: 'solidroad',
    name: 'Solidroad',
    platform: 'PartnerStack',
    category: 'Travel & Expense',
    description: 'Solidroad is a travel and expense management platform provided by GJH Inc that streamlines business trip planning and reporting processes.',
    excerpt: 'Solidroad is a travel and expense management platform provided by GJH Inc that streamlines business trip planning and reporting processes.',
    keywords: ['gjh inc', 'solidroad'],
    url: 'https://solidroad.partnerlinks.io/2734ph6ewbbu',
    logo: '',
    cta: 'Explore Solidroad',
  },
  {
    slug: 'spaceship-com',
    name: 'Spaceship.com',
    platform: 'Impact',
    category: 'Project Management',
    description: 'Spaceship.com is a project management platform that provides tools and features for teams to plan, track, and collaborate on projects in a centralized online workspace.',
    excerpt: 'Spaceship.com is a project management platform that provides tools and features for teams to plan, track, and collaborate on projects in...',
    keywords: ['platform', 'spaceship', 'spaceship.com'],
    url: 'https://spaceship.sjv.io/c/5873369/1794549/21274',
    logo: '',
    cta: 'Explore Spaceship.com',
  },
  {
    slug: 'sps-revenue-recovery',
    name: 'SPS Revenue Recovery',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'SPS Commerce\'s SPS Revenue Recovery is a service that helps businesses recover lost sales and revenue due to errors in their electronic data interchange (EDI) transactions.',
    excerpt: 'SPS Commerce\'s SPS Revenue Recovery is a service that helps businesses recover lost sales and revenue due to errors in their electronic...',
    keywords: ['spscommerce', 'sps revenue recovery', 'gjh inc'],
    url: 'https://ps.spscommerce.com/nma2zx1zlfsn',
    logo: '',
    cta: 'Explore SPS Revenue Recovery',
  },
  {
    slug: 'spytech-software-and-design-inc-sentrypc',
    name: 'Spytech Software and Design, Inc. - sentrypc',
    platform: 'Impact',
    category: 'Cybersecurity & Identity',
    description: 'SentryPC by Spytech Software and Design, Inc.',
    excerpt: 'SentryPC by Spytech Software and Design, Inc.',
    keywords: ['software', 'sentrypc', 'spytech software and design, inc. - sentrypc'],
    url: 'https://sentrypc.7eer.net/c/5873369/200311/3022',
    logo: '',
    cta: 'Explore Spytech Software and Design, Inc. - sentrypc',
  },
  {
    slug: 'surveymonkey',
    name: 'SurveyMonkey',
    platform: 'PartnerStack',
    category: 'Communication & Collaboration',
    description: 'SurveyMonkey is a web-based survey and questionnaire tool developed by SurveyMonkey Inc., allowing users to create and distribute online surveys.',
    excerpt: 'SurveyMonkey is a web-based survey and questionnaire tool developed by SurveyMonkey Inc., allowing users to create and distribute online...',
    keywords: ['gjh inc', 'surveymonkey'],
    url: 'https://get.surveymonkey.com/d6uf2e9u1fei',
    logo: '',
    cta: 'Explore SurveyMonkey',
  },
  {
    slug: 'susengo',
    name: 'Susengo',
    platform: 'Impact',
    category: 'Project Management',
    description: 'Susengo is a project management tool that integrates with Lumibricks to help teams organize and track tasks, workflows, and projects in a centralized platform.',
    excerpt: 'Susengo is a project management tool that integrates with Lumibricks to help teams organize and track tasks, workflows, and projects in...',
    keywords: ['lumibricks', 'susengo'],
    url: 'https://funwhole.sjv.io/c/5873369/1448255/17189',
    logo: '',
    cta: 'Explore Susengo',
  },
  {
    slug: 'susengo-2',
    name: 'Susengo',
    platform: 'Impact',
    category: 'Finance & Accounting',
    description: 'Susengo is a financial management tool that helps users track and categorize expenses by automatically linking receipts to digital records.',
    excerpt: 'Susengo is a financial management tool that helps users track and categorize expenses by automatically linking receipts to digital records.',
    keywords: ['lightailing', 'susengo'],
    url: 'https://lightailing.sjv.io/c/5873369/1448258/17190',
    logo: '',
    cta: 'Explore Susengo',
  },
  {
    slug: 'synder',
    name: 'Synder',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'Synder is a financial automation platform that helps businesses like GJH Inc streamline their accounting processes and reconcile transactions efficiently.',
    excerpt: 'Synder is a financial automation platform that helps businesses like GJH Inc streamline their accounting processes and reconcile...',
    keywords: ['gjh inc', 'synder'],
    url: 'https://partnerstack.synder.com/phkl7wh8uxky-yiw9ba9',
    logo: '',
    cta: 'Explore Synder',
  },
  {
    slug: 'syxsense-by-absolute-security',
    name: 'Syxsense by Absolute Security',
    platform: 'PartnerStack',
    category: 'Cybersecurity & Identity',
    description: 'Syxsense by Absolute Security is a comprehensive cybersecurity solution that provides endpoint management and threat detection capabilities for organizations.',
    excerpt: 'Syxsense by Absolute Security is a comprehensive cybersecurity solution that provides endpoint management and threat detection...',
    keywords: ['gjh inc', 'syxsense by absolute security', 'syxsense'],
    url: 'https://syxsenseinc.partnerlinks.io/3qqspl0fu4yc',
    logo: '',
    cta: 'Explore Syxsense by Absolute Security',
  },
  {
    slug: 'techedology-ltd',
    name: 'TechEdology Ltd',
    platform: 'Impact',
    category: 'HR & Payroll',
    description: 'TechEdology Ltd offers an HR and payroll management tool through its Inspiration Affiliate Programme, providing a digital platform for businesses to streamline their human resources operations.',
    excerpt: 'TechEdology Ltd offers an HR and payroll management tool through its Inspiration Affiliate Programme, providing a digital platform for...',
    keywords: ['app', 'hr', 'techedology ltd', 'tool', 'inspiration-at'],
    url: 'https://inspirationaffiliateprogramme.sjv.io/c/5873369/1474461/17423',
    logo: '',
    cta: 'Explore TechEdology Ltd',
  },
  {
    slug: 'tenable',
    name: 'Tenable',
    platform: 'PartnerStack',
    category: 'Cybersecurity & Identity',
    description: 'Tenable is a cybersecurity platform that provides vulnerability management and risk assessment tools for identifying and prioritizing potential security threats.',
    excerpt: 'Tenable is a cybersecurity platform that provides vulnerability management and risk assessment tools for identifying and prioritizing...',
    keywords: ['gjh inc', 'tenable'],
    url: 'https://shop.tenable.com/uao23qu72u50-vqqg32',
    logo: '',
    cta: 'Explore Tenable',
  },
  {
    slug: 'tidio-poland-sp-z-o-o',
    name: 'Tidio Poland Sp. z o.o.',
    platform: 'Impact',
    category: 'Communication & Collaboration',
    description: 'Tidio Poland Sp.',
    excerpt: 'Tidio Poland Sp.',
    keywords: ['tidio', 'platform', 'tidio poland sp. z o.o.'],
    url: 'https://tidio.pxf.io/c/5873369/1826568/21771',
    logo: '',
    cta: 'Explore Tidio Poland Sp. z o.o.',
  },
  {
    slug: 'trainual',
    name: 'Trainual',
    platform: 'PartnerStack',
    category: 'Operations',
    description: 'Trainual is a platform developed by GJH Inc.',
    excerpt: 'Trainual is a platform developed by GJH Inc.',
    keywords: ['trainual', 'gjh inc'],
    url: 'https://start.trainual.com/vv1v03b9v1sv',
    logo: '',
    cta: 'Explore Trainual',
  },
  {
    slug: 'tru-grit-fitness',
    name: 'Tru Grit Fitness',
    platform: 'Impact',
    category: 'Operations',
    description: 'Tru Grit Fitness offers a digital platform providing operational tools and resources for gyms and fitness studios to manage their business operations more efficiently.',
    excerpt: 'Tru Grit Fitness offers a digital platform providing operational tools and resources for gyms and fitness studios to manage their...',
    keywords: ['trugrit-fitness', 'fitness', 'tru grit fitness'],
    url: 'https://trugritfitness.pxf.io/c/5873369/1442992/17133',
    logo: '',
    cta: 'Explore Tru Grit Fitness',
  },
  {
    slug: 'uperfect',
    name: 'UPERFECT',
    platform: 'Impact',
    category: 'Project Management',
    description: 'UPERFECT is a project management tool that provides real-time monitoring and tracking capabilities through its UPERFECT Monitor feature.',
    excerpt: 'UPERFECT is a project management tool that provides real-time monitoring and tracking capabilities through its UPERFECT Monitor feature.',
    keywords: ['uperfect', 'uperfectmonitor'],
    url: 'https://uperfect.sjv.io/c/5873369/1226533/15155',
    logo: '',
    cta: 'Explore UPERFECT',
  },
  {
    slug: 'vava-international-inc',
    name: 'VAVA INTERNATIONAL INC.',
    platform: 'Impact',
    category: 'Finance & Accounting',
    description: 'VAVA International Inc., a subsidiary of RavPower, offers financial services and products, including affiliate programs for businesses and individuals.',
    excerpt: 'VAVA International Inc., a subsidiary of RavPower, offers financial services and products, including affiliate programs for businesses...',
    keywords: ['vava international inc.', 'ravpower'],
    url: 'https://zebaoaffiliateprogram.pxf.io/c/5873369/1809767/21526',
    logo: '',
    cta: 'Explore VAVA INTERNATIONAL INC.',
  },
  {
    slug: 'vava-international-inc-2',
    name: 'VAVA INTERNATIONAL INC.',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'VAVA International Inc.',
    excerpt: 'VAVA International Inc.',
    keywords: ['vava international inc.', 'parisrhone'],
    url: 'https://parisrhonecom.sjv.io/c/5873369/1811170/21553',
    logo: '',
    cta: 'Explore VAVA INTERNATIONAL INC.',
  },
  {
    slug: 'vava-international-inc-3',
    name: 'VAVA INTERNATIONAL INC.',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'VAVA International Inc.',
    excerpt: 'VAVA International Inc.',
    keywords: ['vava international inc.', 'aspiron'],
    url: 'https://aspironcom.sjv.io/c/5873369/1811185/21554',
    logo: '',
    cta: 'Explore VAVA INTERNATIONAL INC.',
  },
  {
    slug: 'velory',
    name: 'Velory',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'Velory is a financial management platform that provides automated accounting and bookkeeping services for businesses, including invoicing and expense tracking.',
    excerpt: 'Velory is a financial management platform that provides automated accounting and bookkeeping services for businesses, including...',
    keywords: ['gjh inc', 'velory?utm_medium=partnerstack&utm_source={partner_key}', 'velory'],
    url: 'https://try.velory.com/tqcdcc1hr36q',
    logo: '',
    cta: 'Explore Velory',
  },
  {
    slug: 'visualcv',
    name: 'VisualCV',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'VisualCV is a platform that enables users to create and share professional online resumes, CVs, and portfolios with customizable templates and design options.',
    excerpt: 'VisualCV is a platform that enables users to create and share professional online resumes, CVs, and portfolios with customizable...',
    keywords: ['gjh inc', 'visualcv', 'visualcv?utm_medium=influencer_{partner_key}&utm_source=growsumo'],
    url: 'https://visualcv.partnerlinks.io/4lc0fhbeucik',
    logo: '',
    cta: 'Explore VisualCV',
  },
  {
    slug: 'warmy-io',
    name: 'Warmy.io',
    platform: 'PartnerStack',
    category: 'Travel & Expense',
    description: 'Warmy.io is a travel and expense management platform provided by GJH Inc, offering tools for tracking and organizing business-related trips and expenses.',
    excerpt: 'Warmy.io is a travel and expense management platform provided by GJH Inc, offering tools for tracking and organizing business-related...',
    keywords: ['warmy', 'gjh inc', 'warmy.io'],
    url: 'https://warmyio.partnerlinks.io/4gsvkmv3ygqh',
    logo: '',
    cta: 'Explore Warmy.io',
  },
  {
    slug: 'wati-io',
    name: 'Wati.io',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'Wati.io is a financial management platform provided by GJH Inc that offers automated accounting and bookkeeping services for businesses.',
    excerpt: 'Wati.io is a financial management platform provided by GJH Inc that offers automated accounting and bookkeeping services for businesses.',
    keywords: ['gjh inc', 'wati', 'wati.io'],
    url: 'https://affiliates.wati.io/mq5gz7zpyn9a',
    logo: '',
    cta: 'Explore Wati.io',
  },
  {
    slug: 'webai',
    name: 'webAI',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'WebAI is a cloud-based artificial intelligence platform provided by GJH Inc that automates financial data processing and analysis for businesses.',
    excerpt: 'WebAI is a cloud-based artificial intelligence platform provided by GJH Inc that automates financial data processing and analysis for...',
    keywords: ['gjh inc', 'webai'],
    url: 'https://webai.partnerlinks.io/ebngzsqlh3sp',
    logo: '',
    cta: 'Explore webAI',
  },
  {
    slug: 'webflow',
    name: 'Webflow',
    platform: 'PartnerStack',
    category: 'Communication & Collaboration',
    description: 'Webflow is a cloud-based platform that enables users to design, build, and launch custom websites without requiring extensive coding knowledge or technical expertise.',
    excerpt: 'Webflow is a cloud-based platform that enables users to design, build, and launch custom websites without requiring extensive coding...',
    keywords: ['gjh inc', 'webflow'],
    url: 'https://try.webflow.com/6kgb5zamm07j',
    logo: '',
    cta: 'Explore Webflow',
  },
  {
    slug: 'webydo',
    name: 'Webydo',
    platform: 'PartnerStack',
    category: 'Communication & Collaboration',
    description: 'Webydo is a web-based platform that enables teams and designers to collaborate on website design projects in real-time.',
    excerpt: 'Webydo is a web-based platform that enables teams and designers to collaborate on website design projects in real-time.',
    keywords: ['gjh inc', 'webydo'],
    url: 'https://partners.webydo.com/zokqa5ah5xj3',
    logo: '',
    cta: 'Explore Webydo',
  },
  {
    slug: 'whatconverts',
    name: 'WhatConverts',
    platform: 'PartnerStack',
    category: 'Marketing & CRM',
    description: 'WhatConverts is a marketing and sales analytics platform that helps businesses track and manage their lead generation and conversion processes.',
    excerpt: 'WhatConverts is a marketing and sales analytics platform that helps businesses track and manage their lead generation and conversion...',
    keywords: ['gjh inc', 'whatconverts'],
    url: 'https://partners.whatconverts.com/8xtvmdqqowzf',
    logo: '',
    cta: 'Explore WhatConverts',
  },
  {
    slug: 'whistle',
    name: 'Whistle',
    platform: 'Impact',
    category: 'Other',
    description: 'The Whistle is a wearable device that tracks pet activity and health metrics, providing owners with insights through the Wisdom Panel platform.',
    excerpt: 'The Whistle is a wearable device that tracks pet activity and health metrics, providing owners with insights through the Wisdom Panel...',
    keywords: ['health', 'wisdompanel', 'whistle'],
    url: 'https://wisdompanel.pxf.io/c/5873369/1135281/14370',
    logo: '',
    cta: 'Explore Whistle',
  },
  {
    slug: 'wine-express',
    name: 'Wine Express',
    platform: 'Impact',
    category: 'Travel & Expense',
    description: 'Wine Express is a travel and expense management platform that streamlines wine-related purchases for businesses by tracking and reimbursing employee expenses.',
    excerpt: 'Wine Express is a travel and expense management platform that streamlines wine-related purchases for businesses by tracking and...',
    keywords: ['wineexpress', 'wine express'],
    url: 'https://wineexpress.vneoga.net/c/5873369/88200/2181',
    logo: '',
    cta: 'Explore Wine Express',
  },
  {
    slug: 'xero',
    name: 'Xero',
    platform: 'PartnerStack',
    category: 'Finance & Accounting',
    description: 'Xero is a cloud-based accounting software that provides small businesses and accountants with tools for financial management and invoicing.',
    excerpt: 'Xero is a cloud-based accounting software that provides small businesses and accountants with tools for financial management and invoicing.',
    keywords: ['gjh inc', 'xero'],
    url: 'https://referrals.xero.com/k2d5071d97le',
    logo: '',
    cta: 'Explore Xero',
  },
  {
    slug: 'youparcel',
    name: 'YouParcel',
    platform: 'Impact',
    category: 'Operations',
    description: 'The YouParcel platform, offered by Ship7, is a shipping management solution that streamlines parcel tracking and delivery operations for businesses.',
    excerpt: 'The YouParcel platform, offered by Ship7, is a shipping management solution that streamlines parcel tracking and delivery operations for...',
    keywords: ['platform', 'youparcel', 'ship7'],
    url: 'https://ship7com.pxf.io/c/5873369/1495182/17634',
    logo: '',
    cta: 'Explore YouParcel',
  },
];
