import type { PartnerProgram } from './partners'

export const partnerProgramsData: PartnerProgram[] = [
  // PartnerStack programs
  {
    slug: 'clickup',
    name: 'ClickUp',
    platform: 'PartnerStack',
    category: 'Project Management',
    description: 'ClickUp is an all-in-one productivity platform for managing projects, tasks, and collaboration: boards, timelines, time tracking, and custom views that keep delivery visible.',
    excerpt: 'All-in-one project management platform for teams running complex delivery timelines.',
    keywords: ['project management', 'task tracking', 'collaboration', 'delivery timelines', 'boards'],
    url: 'https://try.web.clickup.com/f1xmsye5bi9s-ftpxvl',
    logo: '/partners/clickup.svg',
    cta: 'Explore ClickUp',
    featured: true,
  },
  {
    slug: 'gusto',
    name: 'Gusto',
    platform: 'PartnerStack',
    category: 'HR & Payroll',
    description: 'Gusto simplifies payroll, benefits, and HR for growing businesses: automated filings, workers comp, and reporting in one place.',
    excerpt: 'Payroll, benefits, and HR platform built for growing businesses.',
    keywords: ['payroll', 'HR', 'benefits', 'onboarding', 'small business'],
    url: 'https://get.gusto.com/703bagjmmd7u',
    logo: '/partners/gusto.svg',
    cta: 'Explore Gusto',
  },
  {
    slug: 'onelogin',
    name: 'OneLogin',
    platform: 'PartnerStack',
    category: 'Cybersecurity',
    description: 'OneLogin provides cloud-based identity and access management: single sign-on and multi-factor authentication that secure company apps without slowing people down.',
    excerpt: 'Cloud identity and access management with SSO and MFA.',
    keywords: ['identity management', 'SSO', 'MFA', 'access control', 'security'],
    url: 'https://partnerstack.com/go/onelogin',
    logo: '/partners/onelogin.svg',
    cta: 'Explore OneLogin',
  },
  {
    slug: 'slack',
    name: 'Slack',
    platform: 'PartnerStack',
    category: 'Communication',
    description: 'Slack brings team conversations, files, and tools together in channels, with an integration ecosystem that fits how modern teams already work.',
    excerpt: 'Team communication platform with deep integrations for collaborative work.',
    keywords: ['communication', 'collaboration', 'integrations', 'channels', 'remote teams'],
    url: 'https://partnerstack.com/go/slack',
    logo: '/partners/slack.svg',
    cta: 'Explore Slack',
  },
  {
    slug: 'hubspot',
    name: 'HubSpot',
    platform: 'PartnerStack',
    category: 'Marketing',
    description: 'HubSpot combines CRM, marketing automation, sales pipeline, and customer service in one platform: contacts, campaigns, and reporting that grow with the business.',
    excerpt: 'Integrated CRM and marketing platform for managing customers end to end.',
    keywords: ['CRM', 'marketing automation', 'sales pipeline', 'customer service'],
    url: 'https://partnerstack.com/go/hubspot',
    logo: '/partners/hubspot.svg',
    cta: 'Explore HubSpot',
    featured: true,
  },
  // Impact.com programs
  {
    slug: 'shopify',
    name: 'Shopify',
    platform: 'Impact',
    category: 'E-Commerce',
    description: 'Shopify powers online storefronts for businesses of all sizes: secure checkout, inventory, and multi-channel sales in one platform.',
    excerpt: 'E-commerce platform for secure online storefronts and multi-channel sales.',
    keywords: ['e-commerce', 'online store', 'checkout', 'inventory'],
    url: 'https://impact.com/shopify',
    logo: '/partners/shopify.svg',
    cta: 'Explore Shopify',
  },
  {
    slug: 'segment',
    name: 'Segment (Twilio)',
    platform: 'Impact',
    category: 'Analytics',
    description: 'Segment by Twilio is a customer data platform that collects, cleans, and routes customer data in real time, giving teams one reliable view across tools.',
    excerpt: 'Customer data platform for unified analytics across tools.',
    keywords: ['analytics', 'customer data', 'integrations', 'real-time data'],
    url: 'https://impact.com/segment',
    logo: '/partners/segment.svg',
    cta: 'Explore Segment',
  },
  {
    slug: 'mailchimp',
    name: 'Mailchimp',
    platform: 'Impact',
    category: 'Marketing',
    description: 'Mailchimp provides email marketing automation, audience segmentation, and campaign analytics for staying in touch with customers.',
    excerpt: 'Email marketing automation and audience segmentation.',
    keywords: ['email marketing', 'automation', 'newsletters', 'segmentation'],
    url: 'https://impact.com/mailchimp',
    logo: '/partners/mailchimp.svg',
    cta: 'Explore Mailchimp',
  },
  {
    slug: 'adobe-experience-manager',
    name: 'Adobe Experience Manager',
    platform: 'Impact',
    category: 'Content Management',
    description: 'Adobe Experience Manager is an enterprise content management platform for building and running large, content-rich websites.',
    excerpt: 'Enterprise content management platform for large websites.',
    keywords: ['content management', 'CMS', 'digital experience', 'enterprise'],
    url: 'https://impact.com/adobe-aem',
    logo: '/partners/adobe.svg',
    cta: 'Explore AEM',
  },
  {
    slug: 'stripe',
    name: 'Stripe',
    platform: 'Impact',
    category: 'Payments',
    description: 'Stripe provides payment processing for online businesses: checkout, billing, and payouts with straightforward developer tools.',
    excerpt: 'Payment processing platform for online checkout and billing.',
    keywords: ['payments', 'checkout', 'billing', 'online payments'],
    url: 'https://impact.com/stripe',
    logo: '/partners/stripe.svg',
    cta: 'Explore Stripe',
    featured: true,
  },
];
